image: harkishen/mindtheword_ci_image:latest

stages:
  - build

build:
  stage: build
  script:
    - echo $yandex_translation_key
    - chromium-browser -version
    - npm install -g selenium-webdriver mocha mochawesome chromedriver chromium
    - npm install
    - jspm install bootstrap=npm:bootstrap
    - jspm install
    - npm install gulp
    - gulp build
    - xvfb-run -s "-screen 0 1920x1080x16" -a npm test

