image: harkishen/mindtheword_ci_image:latest

stages:
  - build

build:
  stage: build
  script:
    - npm install
    - jspm install bootstrap=npm:bootstrap
    - jspm install
    - npm install gulp
    - gulp build

