image: harkishen/selenium-ci-aossie-mtw-v1-test:latest

stages:
  - build

build:
  stage: build
  script:
    - apt-get update
    - apt-get install git-core
    - echo "upgrading npm"
    - npm cache clean -f
    - npm install -g n
    - n stable
    - n latest
    - npm install -g npm@latest
    - npm -v
    - npm install -g jspm@beta
    - npm install -g gulp minimatch@3.0.2
    - npm install gulp
    - npm install
    - jspm install
    - gulp build

