image: harkishen/selenium-ci-aossie-mtw-v1-test:latest

stages:
  - build

build:
  stage: build
  script:
    - whoami
    - npm install -g npm@latest
    - npm install -g gulp minimatch@3.0.2
    - npm up -gf npm
    - npm install -g jspm
    - npm install gulp
    - npm install
    - jspm install
    - gulp build

