image: harkishen/selenium-ci-aossie-mtw-v1-test:latest

stages:
  - build

build:
  stage: build
  script:
    - echo "upgrading npm"
    - apt-get install -y nodejs
    - npm -v
    - npm install -g jspm@2.0.0-beta.1
    - npm install -g gulp minimatch@3.0.2
    - npm up -gf npm
    - npm install gulp
    - npm install
    - jspm install
    - gulp build

