image: harkishen/mindtheword_ci_image:latest

stages:
  - build

build:
  stage: build
  script:
    - chromium-browser -version
    - npm install -g selenium-webdriver mocha mochawesome gulp
    - npm install
    - npm install chromedriver@2.46 chromium mocha selenium-webdriver gulp
    - jspm install
    - npm install gulp
    - npm install babel-preset-es2015
    - npm install babel-preset-react
    - gulp build
    - xvfb-run -s "-screen 0 1920x1080x16" -a npm test

